package com.lens.epay.enums;

/**
 * Created by Emir Gökdemir
 * on 17 Nis 2020
 */

public enum OrderStatus {
    TAKEN, APPROVED, PREPARED_FOR_CARGO, REMITTANCE_WAITED, SHIPPED, COMPLETED, RETURN_REQUESTED, REPAID, BACK_SHIPPED, RETURN_REMITTANCE_IS_WAITED, RETURN_SHIPMENT_INFO_WAITED, CANCELLED_BY_CUSTOMER, CANCELLED_BY_SELLER
}
